disabled_rules:
  - line_length
  - nesting
  - variable_name
  - large_tuple
  - weak_delegate
  - class_delegate_protocol
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
custom_rules:
  avoid_print:
    included: ".*.swift"
    excluded: 
      - ".*Test.?\\.swift"
    regex: 'print\('
    name: "print"
    message: "Avoid using print method directly. Use logger"
    severity: warning
  avoid_nslog:
    included: ".*.swift"
    excluded: 
      - ".*Test.?\\.swift"
    regex: 'NSLog\('
    name: "NSLog"
    message: "Avoid using NSLog method directly. Use logger"
    severity: warning
  descriptive_failure_logs:
    included: ".*.swift"
    excluded: ".*Test.?\\.swift"
    regex: '\.(?:warning|error|debug|verbose|info)\(error\.localizedDescription\)'
    name: "descriptive_failure_logs"
    message: "Sometimes localizedDescription is not enough, add a descriptive message and pass in the error"
    severity: warning

